server:
  port: 80
spring:
  application:
    name: cloud-consumer-openfeign-order
  ####Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true #优先使用服务ip进行注册
        service-name: ${spring.application.name}

    openfeign:
      client:
        config:
          cloud-payment-service:
            connect-timeout: 20000
            read-timeout: 20000
          default:
            connect-timeout: 20000
            read-timeout: 20000
      httpclient:
        hc5:
          enabled: true

      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
        response:
          enabled: true
      circuitbreaker:
        enabled: true
        group:
          enabled: true
logging:
  level:
    com:
      atguigu:
        cloud:
          apis:
            PayFeignApi: DEBUG

resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s #神坑的位置，timelimiter 默认限制远程1s，超于1s就超时异常，配置了降级，就走降级逻辑
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50 #设置50%的调用失败时打开断路器，超过失败请求百分⽐CircuitBreaker变为OPEN状态。
        slidingWindowType: COUNT_BASED # 滑动窗口的类型
        slidingWindowSize: 6 #滑动窗口的大小配置，配置TIME_BASED表示2秒
        minimumNumberOfCalls: 6 #断路器计算失败率或慢调用率之前所需的最小样本(每个滑动窗口周期)。
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s #从OPEN到HALF_OPEN状态需要等待的时间
        permittedNumberOfCallsInHalfOpenState: 2 #半开状态允许的最大请求数，默认值为10。
        recordExceptions:
          - java.lang.Exception
    instances:
      cloud-payment-service:
        baseConfig: default